language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install apache2 libapache2-mod-wsgi
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database pkppln;'
  - mysql -uroot pkppln < markstestdb.sql
  - eval "echo \"`cat ${TRAVIS_BUILD_DIR}/wsgi.conf`\"" > /etc/apache2/conf-enabled/wsgi.conf
  - service apache2 restart
script: "py.test tests.py"
