language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database pkppln;'
  - mysql -uroot pkppln < markstestdb.sql
script: "py.test tests.py"
